name: Publish Packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install and build
        run: |
          npm install
          cargo fetch --quiet

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: orqa install publish
