// Tauri IPC commands for artifact graph operations.
//
// All graph operations are delegated to the daemon via HTTP using `DaemonClient`.
// There is no in-process graph building — the daemon is the sole source of truth.
//
// Commands that store health snapshots locally (store_health_snapshot,
// get_health_snapshots) continue to use SQLite directly since snapshot
// persistence is an app-level concern, not a daemon concern.
//
// ID representation: artifact IDs are `String` (opaque file-path-derived keys).
// The `id: String` parameter is intentionally untyped — it is an external
// artifact identifier generated by the daemon and passed back verbatim. A newtype
// over `String` would add no safety guarantee beyond what the daemon already
// enforces by only accepting IDs it issued.

use tauri::{Emitter, Runtime, State};

use crate::daemon_client::{DaemonClient, DaemonGraphHealth};
use crate::domain::health_snapshot::{HealthSnapshot, NewHealthSnapshot};
use crate::error::OrqaError;
use crate::state::AppState;

pub use orqa_engine_types::{
    AppliedFix, ArtifactNode, GraphStats, IntegrityCheck, TraceabilityResult,
};

/// Tauri event name emitted when non-auto-apply transitions are pending.
const STATUS_TRANSITIONS_AVAILABLE_EVENT: &str = "status-transitions-available";

// ---------------------------------------------------------------------------
// Internal helper
// ---------------------------------------------------------------------------

/// Build a `DaemonClient` from the AppState, or return an error.
fn daemon_client(state: &State<'_, AppState>) -> Result<DaemonClient, OrqaError> {
    Ok(state.daemon.client.clone())
}

// ---------------------------------------------------------------------------
// Tauri commands
// ---------------------------------------------------------------------------

/// Get all artifact nodes of a given type (e.g. "epic", "task", "milestone").
///
/// Delegates to GET /artifacts?type=<artifact_type> on the daemon.
#[tauri::command]
pub async fn get_artifacts_by_type(
    artifact_type: String,
    state: State<'_, AppState>,
) -> Result<Vec<ArtifactNode>, OrqaError> {
    if artifact_type.trim().is_empty() {
        return Err(OrqaError::Validation(
            "artifact_type cannot be empty".to_owned(),
        ));
    }
    let client = daemon_client(&state)?;
    let nodes = client.query_artifacts(Some(&artifact_type), None).await?;
    tracing::debug!(r#type = %artifact_type, count = nodes.len(), "get_artifacts_by_type");
    Ok(nodes)
}

/// Read the raw markdown body of an artifact file.
///
/// Looks up the artifact by path via GET /artifacts?type=<all>, then reads its
/// content via GET /artifacts/:id/content. Path traversal is rejected.
#[tauri::command]
pub async fn read_artifact_content(
    path: String,
    state: State<'_, AppState>,
) -> Result<String, OrqaError> {
    if path.trim().is_empty() {
        return Err(OrqaError::Validation("path cannot be empty".to_owned()));
    }
    if path.contains("..") {
        return Err(OrqaError::Validation(
            "path traversal not allowed".to_owned(),
        ));
    }

    // The daemon indexes artifacts by ID, not path. We need to find the ID
    // for the given path by querying all artifacts and matching the path field.
    let client = daemon_client(&state)?;
    let all_nodes = client.query_artifacts(None, None).await?;
    let normalized = path.replace('\\', "/");
    let node = all_nodes
        .into_iter()
        .find(|n| n.path == normalized || n.path.ends_with(&normalized))
        .ok_or_else(|| OrqaError::NotFound(format!("artifact not found at path: {path}")))?;

    client.get_artifact_content(&node.id).await
}

/// Return summary statistics about the artifact graph.
///
/// Delegates to GET /graph/stats on the daemon.
#[tauri::command]
pub async fn get_graph_stats(state: State<'_, AppState>) -> Result<GraphStats, OrqaError> {
    let client = daemon_client(&state)?;
    let resp = client.get_graph_stats().await?;
    // Map daemon's broken_refs field name to the canonical broken_ref_count.
    Ok(GraphStats {
        node_count: resp.node_count,
        edge_count: resp.edge_count,
        orphan_count: resp.orphan_count,
        broken_ref_count: resp.broken_refs,
    })
}

/// Return extended structural health metrics for the artifact graph.
///
/// Delegates to GET /graph/health on the daemon. Returns the daemon's JSON
/// health response shape directly.
#[tauri::command]
pub async fn get_graph_health(state: State<'_, AppState>) -> Result<DaemonGraphHealth, OrqaError> {
    let client = daemon_client(&state)?;
    client.get_graph_health().await
}

/// Return the full traceability chain for a single artifact.
///
/// Delegates to GET /artifacts/:id/traceability on the daemon.
#[tauri::command]
pub async fn get_artifact_traceability(
    id: String,
    state: State<'_, AppState>,
) -> Result<TraceabilityResult, OrqaError> {
    if id.trim().is_empty() {
        return Err(OrqaError::Validation("id cannot be empty".to_owned()));
    }
    let client = daemon_client(&state)?;
    client.get_traceability(&id).await
}

/// Rebuild the artifact graph from disk by asking the daemon to reload.
///
/// Delegates to POST /reload on the daemon. After reload, emits the
/// `status-transitions-available` event if the daemon reports pending transitions.
#[tauri::command]
pub async fn refresh_artifact_graph<R: Runtime>(
    app: tauri::AppHandle<R>,
    state: State<'_, AppState>,
) -> Result<(), OrqaError> {
    tracing::info!(
        subsystem = "graph",
        "refresh_artifact_graph: delegating to daemon"
    );
    let client = daemon_client(&state)?;
    let resp = client.reload().await?;
    tracing::info!(
        subsystem = "graph",
        artifacts = resp.artifacts,
        "refresh_artifact_graph: daemon reloaded"
    );

    // Emit a Tauri event so the frontend refreshes its view.
    if let Err(e) = app.emit("artifact-graph-refreshed", ()) {
        tracing::warn!("[graph] failed to emit artifact-graph-refreshed: {e}");
    }

    // Suppress unused-variable warning; the event constant is used for discoverability.
    let _ = STATUS_TRANSITIONS_AVAILABLE_EVENT;

    Ok(())
}

/// Run integrity checks on the artifact graph and return all findings.
///
/// Delegates to POST /validation/scan on the daemon.
#[tauri::command]
pub async fn run_integrity_scan(
    state: State<'_, AppState>,
) -> Result<Vec<IntegrityCheck>, OrqaError> {
    let client = daemon_client(&state)?;
    let resp = client.run_validation_scan().await?;
    Ok(resp.checks)
}

/// Apply auto-fixable integrity checks and return the list of applied fixes.
///
/// Delegates to POST /validation/fix on the daemon.
#[tauri::command]
pub async fn apply_auto_fixes(state: State<'_, AppState>) -> Result<Vec<AppliedFix>, OrqaError> {
    let client = daemon_client(&state)?;
    let resp = client.run_validation_fix().await?;
    tracing::info!(
        subsystem = "graph",
        fix_count = resp.fixes_applied.len(),
        "apply_auto_fixes: fixes applied"
    );
    Ok(resp.fixes_applied)
}

/// Store a health snapshot with current graph metrics and integrity counts.
///
/// Fetches the current graph health from the daemon, then writes a snapshot
/// to the local SQLite database.
#[tauri::command]
pub async fn store_health_snapshot(
    error_count: i64,
    warning_count: i64,
    state: State<'_, AppState>,
) -> Result<HealthSnapshot, OrqaError> {
    let client = daemon_client(&state)?;
    let health = client.get_graph_health().await?;

    let storage = state.db.get()?;

    let project = storage
        .projects()
        .get_active()?
        .ok_or_else(|| OrqaError::NotFound("no active project".to_owned()))?;

    Ok(storage.health().create(
        project.id,
        &NewHealthSnapshot {
            node_count: health.total_nodes as i64,
            edge_count: health.total_edges as i64,
            broken_ref_count: health.broken_ref_count as i64,
            error_count,
            warning_count,
            largest_component_ratio: health.largest_component_ratio,
            avg_degree: health.avg_degree,
            pillar_traceability: health.pillar_traceability,
            outlier_count: health.outlier_count as i64,
            outlier_percentage: health.outlier_percentage,
            delivery_connectivity: health.delivery_connectivity,
            learning_connectivity: health.learning_connectivity,
        },
    )?)
}

/// Update a single YAML frontmatter field in an artifact file.
///
/// Delegates to PUT /artifacts/:id on the daemon. The path argument is used to
/// look up the artifact ID in the daemon's graph.
#[tauri::command]
pub async fn update_artifact_field(
    path: String,
    field: String,
    value: String,
    state: State<'_, AppState>,
) -> Result<(), OrqaError> {
    if path.trim().is_empty() {
        return Err(OrqaError::Validation("path cannot be empty".to_owned()));
    }
    if path.contains("..") {
        return Err(OrqaError::Validation(
            "path traversal not allowed".to_owned(),
        ));
    }
    if field.trim().is_empty() {
        return Err(OrqaError::Validation("field cannot be empty".to_owned()));
    }

    // Find the artifact ID for the given path.
    let client = daemon_client(&state)?;
    let all_nodes = client.query_artifacts(None, None).await?;
    let normalized = path.replace('\\', "/");
    let node = all_nodes
        .into_iter()
        .find(|n| n.path == normalized || n.path.ends_with(&normalized))
        .ok_or_else(|| OrqaError::NotFound(format!("artifact not found: {path}")))?;

    tracing::debug!(
        subsystem = "graph",
        artifact_id = %node.id,
        field = %field,
        "update_artifact_field"
    );
    client.update_artifact_field(&node.id, &field, &value).await
}

/// Get the most recent health snapshots for the active project.
///
/// This query is local-only — snapshots are stored in the app's SQLite database.
#[tauri::command]
pub fn get_health_snapshots(
    limit: Option<i64>,
    state: State<'_, AppState>,
) -> Result<Vec<HealthSnapshot>, OrqaError> {
    let storage = state.db.get()?;

    let project = storage
        .projects()
        .get_active()?
        .ok_or_else(|| OrqaError::NotFound("no active project".to_owned()))?;

    Ok(storage
        .health()
        .get_recent(project.id, limit.unwrap_or(30))?)
}

#[cfg(test)]
mod tests {
    #[test]
    fn artifact_type_validation_rejects_empty() {
        let artifact_type = "";
        assert!(artifact_type.trim().is_empty());
    }

    #[test]
    fn path_traversal_rejected() {
        let path = "../../../etc/passwd";
        assert!(path.contains(".."));
    }

    #[test]
    fn path_empty_rejected() {
        let path = "   ";
        assert!(path.trim().is_empty());
    }
}
