/**
 * .prettierignore generator for the OrqaStudio enforcement pipeline.
 *
 * Produces a .prettierignore file at the project root combining:
 *   - Universal build-artifact excludes (node_modules, dist, build, target)
 *   - Framework-specific excludes (src-tauri — Rust code formatted by rustfmt)
 *   - Governance excludes (.orqa — markdown formatted by markdownlint, not prettier)
 *   - Generated file excludes (lock files, *.generated.ts)
 *
 * This replaces the previously hand-maintained .prettierignore.  The source of
 * truth is this generator script; the output is a derived file that should not
 * be edited directly.
 *
 * Invocation (by daemon watcher or orqa install):
 *   node generate-prettierignore.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path>
 */

import { parseArgs, resolveOutputPath, writeOutput } from "../../../shared/generator-utils";

/**
 * Standard exclusion categories.  Each section has a comment header and a list
 * of patterns.  The order matches the conventional .prettierignore layout.
 */
const SECTIONS: Array<{ header: string; patterns: string[] }> = [
	{
		header: "Build artifacts",
		patterns: ["build/", "dist/", "target/", ".svelte-kit/"],
	},
	{
		header: "Dependencies",
		patterns: ["node_modules/"],
	},
	{
		header: "Generated files",
		patterns: ["*.generated.ts", "src-tauri/"],
	},
	{
		header: "Governance artifacts (markdown formatted by markdownlint, not prettier)",
		patterns: [".orqa/", ".state/"],
	},
	{
		header: "Lock files",
		patterns: ["package-lock.json", "pnpm-lock.yaml"],
	},
];

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();

const lines: string[] = [
	"# GENERATED by @orqastudio/plugin-core-framework — do not edit manually.",
	"# Regenerate with: orqa enforce --prettierignore",
	"",
];

for (const section of SECTIONS) {
	lines.push(`# ${section.header}`);
	for (const pattern of section.patterns) {
		lines.push(pattern);
	}
	lines.push("");
}

const content = lines.join("\n");
const outputPath = resolveOutputPath(args, "prettierignore");
writeOutput(outputPath, content);
