/**
 * Git hooks generator for the OrqaStudio enforcement pipeline.
 *
 * Writes pre-commit and post-commit scripts to the --output directory
 * (.githooks/) with a generated header. The hooks delegate to `orqa enforce`
 * so that all enforcement logic stays in the CLI, not the hook scripts.
 *
 * Plugin contributions via rule files are NOT yet consumed — the hook scripts
 * are assembled from defaults only. Rule-based contributions will be added
 * when the hook composition model is finalised.
 *
 * Invocation:
 *   node generate-githooks.ts \
 *     --project-root <path> \
 *     --output <path>       \   (directory, e.g. .githooks/)
 *     --rules-dir <path>    \
 *     [--dry-run]
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { parseArgs } from "../../../shared/generator-utils";

const GENERATED_HEADER = `# Generated by @orqastudio/plugin-core-framework — do not edit manually.
# Re-generate with: orqa install`;

/**
 * The pre-commit hook script body.
 * Delegates all enforcement to `orqa enforce --staged`.
 */
const PRE_COMMIT_BODY = `#!/usr/bin/env bash
${GENERATED_HEADER}
set -u

if [ "\${ORQA_SKIP_HOOKS:-}" = "1" ]; then
  echo "WARNING: ORQA_SKIP_HOOKS=1 — skipping all pre-commit checks"
  exit 0
fi

if ! command -v orqa &> /dev/null; then
  PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
  if [ -f "$PROJECT_ROOT/cli/dist/cli.js" ]; then
    ORQA="node $PROJECT_ROOT/cli/dist/cli.js"
  else
    echo "WARNING: orqa CLI not available — skipping pre-commit checks"
    exit 0
  fi
else
  ORQA="orqa"
fi

echo "=== Pre-commit: Running enforcement checks ==="
$ORQA enforce --staged
exit $?
`;

/**
 * The post-commit hook script body.
 * Auto-pushes to remote after every commit (RULE-f609242f).
 */
const POST_COMMIT_BODY = `#!/usr/bin/env bash
${GENERATED_HEADER}
#
# Auto-pushes to the remote after every commit (RULE-f609242f).
#
# Behavior:
#   - Sets upstream on first push for new branches
#   - Skips push during rebase, merge, cherry-pick, revert, or bisect
#   - Warns on failure but does not block (post-commit cannot prevent the commit)

# Do not use set -e -- a push failure must not crash the hook
set -uo pipefail

# ── Skip during automated git operations ──────────────────────────────────

GIT_DIR=$(git rev-parse --git-dir)

# Rebase in progress
if [ -d "$GIT_DIR/rebase-merge" ] || [ -d "$GIT_DIR/rebase-apply" ]; then
  exit 0
fi

# Merge in progress
if [ -f "$GIT_DIR/MERGE_HEAD" ]; then
  exit 0
fi

# Cherry-pick in progress
if [ -f "$GIT_DIR/CHERRY_PICK_HEAD" ]; then
  exit 0
fi

# Revert in progress
if [ -f "$GIT_DIR/REVERT_HEAD" ]; then
  exit 0
fi

# ── Skip if no remote configured ──────────────────────────────────────────

if ! git remote get-url origin &>/dev/null; then
  exit 0
fi

# ── Push ──────────────────────────────────────────────────────────────────

BRANCH=$(git branch --show-current)

# Detached HEAD (e.g., during bisect) -- skip
if [ -z "$BRANCH" ]; then
  exit 0
fi

# Check if upstream is set
if git rev-parse --abbrev-ref --symbolic-full-name "@{u}" &>/dev/null; then
  if ! git push 2>&1; then
    echo ""
    echo "WARNING: post-commit push failed. Run 'git push' manually."
    echo ""
  fi
else
  if ! git push -u origin "$BRANCH" 2>&1; then
    echo ""
    echo "WARNING: post-commit push failed. Run 'git push -u origin $BRANCH' manually."
    echo ""
  fi
fi
`;

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();

// --output is the .githooks/ directory when invoked from the plugin system.
// Resolve it relative to project root if not absolute.
const hooksDir = path.isAbsolute(args.output)
	? args.output
	: path.join(args.projectRoot, args.output);

// When dry-run, redirect to .state/dry-run/githooks/
const outputDir = args.dryRun
	? path.join(args.projectRoot, ".state", "dry-run", "githooks")
	: hooksDir;

fs.mkdirSync(outputDir, { recursive: true });

/**
 * Write a hook script to the output directory and make it executable.
 * @param name - Hook filename (e.g., "pre-commit").
 * @param content - Shell script content to write.
 */
function writeHook(name: string, content: string): void {
	const hookPath = path.join(outputDir, name);
	try {
		fs.writeFileSync(hookPath, content, { encoding: "utf-8" });
		// chmod +x — ignored silently on platforms that don't support it (Windows)
		try {
			fs.chmodSync(hookPath, 0o755);
		} catch {
			// Not supported on Windows; git will still execute the hook via bash
		}
		process.stderr.write(`[generator] wrote ${hookPath}\n`);
	} catch (err) {
		process.stderr.write(`[generator] failed to write ${hookPath}: ${err}\n`);
		process.exit(1);
	}
}

writeHook("pre-commit", PRE_COMMIT_BODY);
writeHook("post-commit", POST_COMMIT_BODY);
