/**
 * markdownlint config generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=markdownlint, and produces a self-contained .markdownlint.json at
 * --output.
 *
 * Each enforcement entry may specify:
 *   - `rule`: the markdownlint rule name or alias (e.g., "MD013", "line-length")
 *   - `enabled`: boolean — true to enable, false to disable the rule
 *   - `options`: a mapping of rule-specific configuration values
 *
 * The generator starts from conservative OrqaStudio defaults and applies
 * overrides from rule files. Later entries for the same rule win.
 *
 * Invocation:
 *   node generate-markdownlint-config.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
  parseArgs,
  scanRules,
  filterByEngine,
  resolveOutputPath,
  writeOutput,
  type EnforcementEntry,
} from "../../../shared/generator-utils";

/**
 * Canonical markdownlint defaults for OrqaStudio projects.
 *
 * Most rules are enabled at default settings. Specific rules are adjusted to
 * match OrqaStudio's documentation style: longer line length, code blocks
 * allowed in headings, etc.
 */
const DEFAULT_CONFIG: Record<string, unknown> = {
  default: true,
  // MD013 — line length: disabled because documentation often has long links
  // and code snippets that cannot be wrapped without harming readability.
  MD013: false,
  // MD033 — inline HTML: allowed in documentation for callout blocks and
  // rendered table improvements.
  MD033: false,
  // MD041 — first line should be a top-level heading: disabled for
  // frontmatter-only files that have no H1.
  MD041: false,
};

/**
 * Apply enforcement entry overrides to the base config.
 *
 * An entry with `enabled: false` disables the rule entirely (sets it to
 * false). An entry with `enabled: true` and no `options` enables the rule
 * with defaults (sets it to true). An entry with both `enabled: true` and
 * `options` sets the rule to the options object.
 *
 * Entries without a `rule` field are silently skipped.
 */
function applyOverrides(
  base: Readonly<Record<string, unknown>>,
  entries: readonly EnforcementEntry[],
): Record<string, unknown> {
  const result = { ...base };
  for (const entry of entries) {
    const ruleName = entry["rule"] as string | undefined;
    if (!ruleName) continue;

    const enabled = entry["enabled"] as boolean | undefined;
    const options = entry["options"] as Record<string, unknown> | undefined;

    if (enabled === false) {
      result[ruleName] = false;
    } else if (options && Object.keys(options).length > 0) {
      result[ruleName] = options;
    } else {
      // enabled === true or unset — use default rule settings.
      result[ruleName] = true;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);
const relevant = filterByEngine(allRules, "markdownlint");
const entries = relevant.flatMap((r) => r.enforcement);

const config = applyOverrides(DEFAULT_CONFIG, entries);

const output = {
  _generated:
    "Generated by @orqastudio/plugin-core-framework — do not edit manually.",
  ...config,
};

const content = JSON.stringify(output, null, 2) + "\n";
const outputPath = resolveOutputPath(args, "markdownlint");
writeOutput(outputPath, content);
