/**
 * Prettier config generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=prettier, and produces a self-contained .prettierrc JSON at --output.
 *
 * Each enforcement entry may specify:
 *   - `option`: the Prettier option name (e.g., "printWidth", "tabWidth")
 *   - `value`: the value to set
 *
 * The generator starts from canonical OrqaStudio defaults and applies any
 * per-option overrides found in rule files. Later entries for the same option
 * win.
 *
 * Invocation:
 *   node generate-prettier-config.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
	parseArgs,
	scanRules,
	filterByEngine,
	resolveOutputPath,
	writeOutput,
	type EnforcementEntry,
} from "../../../shared/generator-utils";

/**
 * Canonical Prettier defaults for OrqaStudio projects.
 *
 * These represent the agreed formatting baseline. Rule files can override
 * individual options.
 */
const DEFAULT_OPTIONS: Record<string, unknown> = {
	printWidth: 100,
	tabWidth: 2,
	useTabs: true,
	semi: true,
	singleQuote: false,
	trailingComma: "all",
	bracketSpacing: true,
	arrowParens: "always",
	endOfLine: "lf",
	plugins: ["prettier-plugin-svelte"],
	overrides: [
		{
			files: "*.svelte",
			options: { parser: "svelte" },
		},
	],
};

/**
 * Apply per-option overrides from rule enforcement entries.
 *
 * Entries missing either `option` or `value` are silently skipped.
 * @param base
 * @param entries
 */
function applyOverrides(
	base: Readonly<Record<string, unknown>>,
	entries: readonly EnforcementEntry[],
): Record<string, unknown> {
	const result = { ...base };
	for (const entry of entries) {
		const option = entry["option"] as string | undefined;
		const value = entry["value"];
		if (option !== undefined && value !== undefined) {
			result[option] = value;
		}
	}
	return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);
const relevant = filterByEngine(allRules, "prettier");
const entries = relevant.flatMap((r) => r.enforcement);

const options = applyOverrides(DEFAULT_OPTIONS, entries);

// Prepend a _generated comment key so readers understand the file's provenance.
const output = {
	_generated: "Generated by @orqastudio/plugin-core-framework — do not edit manually.",
	...options,
};

const content = JSON.stringify(output, null, 2) + "\n";
const outputPath = resolveOutputPath(args, "prettier");
writeOutput(outputPath, content);
