#!/usr/bin/env bash
# Stop hook — writes session state and provides pre-commit checklist
#
# Session state is written to tmp/session-state.md so the next session
# can pick up exactly where this one left off.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
OUTPUT=""

# ─── Session State ────────────────────────────────────────────────────────────
# Write structured session state for the next session to pick up.
# The agent should have written this already via the orchestrator protocol,
# but we gather what we can from git state as a safety net.

SESSION_FILE="$PROJECT_DIR/tmp/session-state.md"
mkdir -p "$PROJECT_DIR/tmp"

# Find active epics and tasks from .orqa/
ACTIVE_EPICS=""
if [ -d "$PROJECT_DIR/.orqa/delivery/epics" ]; then
  ACTIVE_EPICS=$(grep -l "^status: active" "$PROJECT_DIR"/.orqa/delivery/epics/*.md 2>/dev/null | while read f; do
    id=$(grep "^id:" "$f" | head -1 | sed 's/^id:\s*//' | tr -d '"')
    title=$(grep "^title:" "$f" | head -1 | sed 's/^title:\s*//' | tr -d '"')
    echo "- $id: $title"
  done || true)
fi

ACTIVE_TASKS=""
if [ -d "$PROJECT_DIR/.orqa/delivery/tasks" ]; then
  ACTIVE_TASKS=$(grep -l "^status: active" "$PROJECT_DIR"/.orqa/delivery/tasks/*.md 2>/dev/null | while read f; do
    id=$(grep "^id:" "$f" | head -1 | sed 's/^id:\s*//' | tr -d '"')
    title=$(grep "^title:" "$f" | head -1 | sed 's/^title:\s*//' | tr -d '"')
    echo "- $id: $title"
  done || true)
fi

# Get recent commits from this session (last 5)
RECENT_COMMITS=$(cd "$PROJECT_DIR" && git log --oneline -5 2>/dev/null || true)

# Get uncommitted changes summary
UNCOMMITTED_FILES=$(cd "$PROJECT_DIR" && git status --short 2>/dev/null || true)
UNCOMMITTED_COUNT=$(echo "$UNCOMMITTED_FILES" | grep -c '.' 2>/dev/null || echo "0")

# Write session state (only if the agent hasn't written a richer one)
# Check if the file was written recently (within last 60 seconds) by the agent
WRITE_STATE=true
if [ -f "$SESSION_FILE" ]; then
  # If file was modified in the last 60 seconds, the agent likely wrote it — don't overwrite
  if find "$SESSION_FILE" -mmin -1 2>/dev/null | grep -q .; then
    WRITE_STATE=false
  fi
fi

if [ "$WRITE_STATE" = true ]; then
  cat > "$SESSION_FILE" << SESSIONEOF
## Session: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

### Active Epics
${ACTIVE_EPICS:-No active epics found}

### Active Tasks
${ACTIVE_TASKS:-No active tasks found}

### Recent Commits
${RECENT_COMMITS:-No commits in this session}

### Uncommitted Changes
${UNCOMMITTED_COUNT} files with uncommitted changes

### Notes
Session state auto-generated by stop hook. If the orchestrator wrote a more detailed state, this file was preserved.
SESSIONEOF
fi

# ─── Pre-Stop Output ──────────────────────────────────────────────────────────

# Check for open worktrees
MAIN_DIR=$(cd "$PROJECT_DIR" && git rev-parse --show-toplevel 2>/dev/null || echo "$PROJECT_DIR")
WORKTREES=$(cd "$PROJECT_DIR" && git worktree list 2>/dev/null | grep -v "$MAIN_DIR" || true)
if [ -n "$WORKTREES" ]; then
  OUTPUT="${OUTPUT}WARNING: Open worktrees detected — merge and clean up before reporting task complete:\n${WORKTREES}\n\n"
fi

if [ "$UNCOMMITTED_COUNT" -gt 0 ]; then
  OUTPUT="${OUTPUT}UNCOMMITTED CHANGES: ${UNCOMMITTED_COUNT} files. Commit or stash before ending session.\n\n"
fi

cat <<'EOF'
SESSION END PROTOCOL:

Before stopping, the orchestrator MUST:
1. Write session state to tmp/session-state.md:
   - Scope: which epic/task was in focus
   - Done: what was completed this session
   - In Progress: what's partially done
   - Next: what should happen next session
   - Blockers: anything blocking progress
2. Commit all work
3. Verify checks pass (make check)

PRE-STOP CHECKLIST:
- All checks pass (make check)
- No stub/mock/placeholder patterns in committed code
- Changes are within task scope
- No TODO comments or stubs added
- Documentation updated if behaviour changed
- Session state written to tmp/session-state.md

FORBIDDEN:
- NEVER use --no-verify — fix the errors instead
- NEVER skip pre-commit hooks
- NEVER end a session with uncommitted changes
EOF

if [ -n "$OUTPUT" ]; then
  echo ""
  echo -e "$OUTPUT"
fi

exit 0
