/**
 * Clippy config generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=clippy, and produces a self-contained clippy.toml at --output.
 *
 * Each enforcement entry may specify:
 *   - `lint`: the clippy lint name (e.g., "clippy::unwrap_used")
 *   - `level`: "deny", "warn", or "allow"
 *
 * The generator produces a flat TOML file. Clippy TOML supports `warn`,
 * `deny`, and `allow` arrays at the top level. Lints without a `level` field
 * default to "warn".
 *
 * Invocation:
 *   node generate-clippy-config.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
  parseArgs,
  scanRules,
  filterByEngine,
  resolveOutputPath,
  writeOutput,
  type EnforcementEntry,
} from "../../../shared/generator-utils";

type ClippyLevel = "deny" | "warn" | "allow";

interface ClippyLintGroup {
  deny: string[];
  warn: string[];
  allow: string[];
}

/**
 * Normalise a raw level string to a ClippyLevel.
 *
 * Treats unrecognised or absent values as "warn" since that is the least
 * disruptive default.
 */
function normaliseLevel(raw: unknown): ClippyLevel {
  if (raw === "deny" || raw === "error") return "deny";
  if (raw === "allow" || raw === "off") return "allow";
  return "warn";
}

/**
 * Group lint names from enforcement entries by their level.
 *
 * Entries without a `lint` field are skipped.
 */
function groupByLevel(entries: EnforcementEntry[]): ClippyLintGroup {
  const groups: ClippyLintGroup = { deny: [], warn: [], allow: [] };
  for (const entry of entries) {
    const lint = entry["lint"] as string | undefined;
    if (!lint) continue;
    const level = normaliseLevel(entry["level"]);
    groups[level].push(lint);
  }
  return groups;
}

/**
 * Render a TOML array of strings, one entry per line.
 *
 * Returns an empty string when the array is empty so the section is omitted.
 */
function renderTomlArray(key: string, values: string[]): string {
  if (values.length === 0) return "";
  const items = values.map((v) => `  "${v}",`).join("\n");
  return `${key} = [\n${items}\n]\n`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);
const relevant = filterByEngine(allRules, "clippy");
const entries = relevant.flatMap((r) => r.enforcement);

const groups = groupByLevel(entries);

const lines: string[] = [
  "# GENERATED by @orqastudio/plugin-rust — do not edit manually.",
  "# Source: .orqa/learning/rules/ (filtered by engine: clippy)",
  "# Regenerated by daemon watcher on rule file changes.",
  "",
];

const denySection = renderTomlArray("deny", groups.deny);
const warnSection = renderTomlArray("warn", groups.warn);
const allowSection = renderTomlArray("allow", groups.allow);

if (denySection) lines.push(denySection);
if (warnSection) lines.push(warnSection);
if (allowSection) lines.push(allowSection);

// If no rule files contributed lint entries, emit an empty valid TOML file
// so the tool can still run.
if (!denySection && !warnSection && !allowSection) {
  lines.push("# No mechanical enforcement entries found for engine: clippy");
}

const content = lines.join("\n");
const outputPath = resolveOutputPath(args, "clippy");
writeOutput(outputPath, content);
