/**
 * rustfmt config generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=rustfmt, and produces a self-contained .rustfmt.toml at --output.
 *
 * Each enforcement entry may specify:
 *   - `option`: the rustfmt option name (e.g., "max_width")
 *   - `value`: the value to set (string, number, or boolean)
 *
 * The generator produces a flat TOML file. Options from rule files augment
 * the canonical defaults below. Later entries override earlier entries for
 * the same option.
 *
 * Invocation:
 *   node generate-rustfmt-config.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
  parseArgs,
  scanRules,
  filterByEngine,
  resolveOutputPath,
  writeOutput,
  type EnforcementEntry,
} from "../../../shared/generator-utils";

/**
 * Canonical rustfmt defaults for OrqaStudio projects.
 *
 * These represent the agreed-upon base formatting settings. Rule files can
 * override individual options.
 */
const DEFAULT_OPTIONS: Record<string, unknown> = {
  edition: "2021",
  max_width: 100,
  tab_spaces: 4,
  use_small_heuristics: "Default",
  imports_granularity: "Crate",
  group_imports: "StdExternalCrate",
};

/**
 * Apply per-option overrides from rule enforcement entries.
 *
 * Entries missing either `option` or `value` are silently skipped.
 */
function applyOverrides(
  base: Readonly<Record<string, unknown>>,
  entries: readonly EnforcementEntry[],
): Record<string, unknown> {
  const result = { ...base };
  for (const entry of entries) {
    const option = entry["option"] as string | undefined;
    const value = entry["value"];
    if (option !== undefined && value !== undefined) {
      result[option] = value;
    }
  }
  return result;
}

/**
 * Render a TOML value. Strings are quoted; booleans and numbers are bare.
 */
function toTomlValue(v: unknown): string {
  if (typeof v === "string") return `"${v}"`;
  return String(v);
}

/**
 * Render a flat TOML file from a key/value map.
 */
function renderToml(options: Record<string, unknown>): string {
  return Object.entries(options)
    .map(([k, v]) => `${k} = ${toTomlValue(v)}`)
    .join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);
const relevant = filterByEngine(allRules, "rustfmt");
const entries = relevant.flatMap((r) => r.enforcement);

const options = applyOverrides(DEFAULT_OPTIONS, entries);

const content = [
  "# GENERATED by @orqastudio/plugin-rust — do not edit manually.",
  "# Source: .orqa/learning/rules/ (filtered by engine: rustfmt)",
  "# Regenerated by daemon watcher on rule file changes.",
  "",
  renderToml(options),
  "",
].join("\n");

const outputPath = resolveOutputPath(args, "rustfmt");
writeOutput(outputPath, content);
