// SeaORM entity for the `devtools_sessions` table.
//
// Each open/close cycle of the devtools window produces one devtools_session
// row. The session ID is a UUID v4 string generated by the devtools app at
// startup. The event_count column is a denormalized counter maintained by the
// repository on each insert_events call.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// SeaORM entity model for a row in the `devtools_sessions` table.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "devtools_sessions")]
pub struct Model {
    /// UUID v4 session identifier (TEXT PRIMARY KEY).
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    /// Unix millisecond timestamp when the session started.
    pub started_at: i64,
    /// Unix millisecond timestamp when the session ended; `None` if still active.
    pub ended_at: Option<i64>,
    /// User-editable label; `None` means show an auto-generated name.
    pub label: Option<String>,
    /// Denormalized count of events in this session.
    pub event_count: i64,
}

/// Relations from `devtools_sessions` to other tables.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// A devtools session has many events.
    #[sea_orm(has_many = "super::devtools_events::Entity")]
    DevtoolsEvents,
}

impl Related<super::devtools_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DevtoolsEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
