/**
 * ESLint config generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=eslint, and produces a self-contained eslint.config.js at --output.
 *
 * The generated config is functionally equivalent to app/eslint.config.js:
 * - typescript-eslint recommended rules
 * - eslint-plugin-svelte flat/recommended for .svelte files
 * - eslint-plugin-jsdoc flat/recommended-typescript
 * - Per-rule overrides from enforcement entries
 *
 * Invocation:
 *   node generate-eslint-config.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
  parseArgs,
  scanRules,
  filterByEngine,
  resolveOutputPath,
  writeOutput,
  type EnforcementEntry,
  type ParsedRule,
} from "../../../shared/generator-utils";

/** Maps ESLint severity strings to their canonical form. */
function normaliseSeverity(raw: unknown): "error" | "warn" | "off" {
  if (raw === "error" || raw === 0) return "error";
  if (raw === "warn" || raw === 1) return "warn";
  return "off";
}

/**
 * Build the rules object from enforcement entries filtered for the eslint
 * engine. Entries without a `rule` field are skipped.
 */
function buildRulesFromEntries(
  entries: EnforcementEntry[],
): Record<string, unknown> {
  const rules: Record<string, unknown> = {};

  for (const entry of entries) {
    const ruleName = entry["rule"] as string | undefined;
    if (!ruleName) continue;

    const severity = normaliseSeverity(entry["severity"]);
    const options = entry["options"] as Record<string, unknown> | undefined;

    if (options && Object.keys(options).length > 0) {
      rules[ruleName] = [severity, options];
    } else {
      rules[ruleName] = severity;
    }
  }

  return rules;
}

/**
 * Render the generated eslint.config.js content as a string.
 *
 * The output imports typescript-eslint, eslint-plugin-svelte, and
 * eslint-plugin-jsdoc using project-level NPM packages. No @orqastudio/*
 * imports are used so the config is self-contained at runtime.
 */
function renderEslintConfig(
  tsRules: Record<string, unknown>,
  svelteRules: Record<string, unknown>,
): string {
  const tsRulesStr = renderRulesObject(tsRules, 4);
  const svelteRulesStr = renderRulesObject(svelteRules, 4);

  return `// GENERATED by @orqastudio/plugin-typescript — do not edit manually.
// Source: .orqa/learning/rules/ (filtered by engine: eslint)
// Regenerated by daemon watcher on rule file changes.

import tseslint from "typescript-eslint";
import sveltePlugin from "eslint-plugin-svelte";
import jsdocPlugin from "eslint-plugin-jsdoc";
import globals from "globals";

export default tseslint.config(
  // ── Layer 1: TypeScript base ──────────────────────────────────────────
  // typescript-eslint recommended + per-rule overrides from enforcement rules.
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts"],
    rules: {
${tsRulesStr}
    },
  },
  {
    files: ["**/*.test.ts", "**/*.test.js", "**/__tests__/**"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["**/*.worker.ts", "**/logger.ts", "**/dev-console.ts"],
    rules: {
      "no-console": "off",
    },
  },

  // ── Layer 2: Svelte ───────────────────────────────────────────────────
  // Svelte flat/recommended + TypeScript parser for .svelte files.
  ...sveltePlugin.configs["flat/recommended"],
  {
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {
${svelteRulesStr}
    },
  },

  // ── Layer 3: Environment globals ──────────────────────────────────────
  // Tauri apps run in both browser (webview) and node (build tooling).
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  // ── Layer 4: Documentation enforcement ───────────────────────────────
  // Every exported function and class must have a JSDoc description.
  jsdocPlugin.configs["flat/recommended-typescript"],
  {
    files: ["**/*.ts", "**/*.svelte.ts"],
    rules: {
      "jsdoc/require-jsdoc": ["warn", {
        require: {
          FunctionDeclaration: true,
          MethodDefinition: true,
          ClassDeclaration: true,
        },
        publicOnly: true,
      }],
      "jsdoc/require-description": "warn",
    },
  },

  // ── Layer 5: Ignores ──────────────────────────────────────────────────
  {
    ignores: [
      "build/",
      ".svelte-kit/",
      "node_modules/",
      "dist/",
    ],
  },
);
`;
}

/**
 * Render a rules object as indented key-value lines for embedding in the
 * generated config.
 */
function renderRulesObject(
  rules: Record<string, unknown>,
  indent: number,
): string {
  const pad = " ".repeat(indent);
  return Object.entries(rules)
    .map(([k, v]) => `${pad}"${k}": ${JSON.stringify(v)},`)
    .join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);

// Split entries by file type so we can place them in the correct config block.
const tsEntries = filterByEngine(allRules, "eslint").flatMap(
  (r: ParsedRule) => r.enforcement,
);
const svelteEntries = filterByEngine(allRules, "eslint-svelte").flatMap(
  (r: ParsedRule) => r.enforcement,
);

const tsRules = buildRulesFromEntries(tsEntries);
const svelteRules = buildRulesFromEntries(svelteEntries);

const content = renderEslintConfig(tsRules, svelteRules);
const outputPath = resolveOutputPath(args, "eslint");
writeOutput(outputPath, content);
