/**
 * Workspace tsconfig.json generator for the OrqaStudio enforcement pipeline.
 *
 * Discovers all TypeScript packages in the monorepo by reading the root
 * package.json `workspaces` field, and generates a tsconfig.json with an
 * `include` array covering all source directories.  This replaces the
 * previously hand-maintained root tsconfig.json.
 *
 * The generated config:
 *   - Extends tsconfig.base.json (generated by generate-tsconfig.ts)
 *   - Includes all TS source paths discovered from workspaces
 *   - Sets noEmit: true (workspace config is for IDE type-checking only)
 *
 * Invocation (by daemon watcher or orqa install):
 *   node generate-tsconfig-workspace.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path>
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { parseArgs, resolveOutputPath, writeOutput } from "../../../shared/generator-utils";

/**
 * Discover TypeScript source directories from the monorepo workspace layout.
 *
 * Reads root package.json workspaces, expands glob patterns to real
 * directories, and filters to those containing TypeScript source.
 * @param projectRoot - Absolute path to the project root.
 * @returns Array of relative include paths (e.g. "libs/sdk/src/**\/*.ts").
 */
function discoverIncludes(projectRoot: string): string[] {
	const pkgPath = path.join(projectRoot, "package.json");
	if (!fs.existsSync(pkgPath)) return [];

	const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
	const workspaces: string[] = Array.isArray(pkg.workspaces)
		? pkg.workspaces
		: (pkg.workspaces?.packages ?? []);

	const includes: string[] = [];

	for (const pattern of workspaces) {
		// Expand simple glob: "libs/*" → all dirs in libs/
		const base = pattern.replace(/\/?\*$/, "");
		const baseDir = path.join(projectRoot, base);

		if (!fs.existsSync(baseDir) || !fs.statSync(baseDir).isDirectory()) continue;

		if (pattern.endsWith("/*")) {
			// Wildcard — scan subdirectories
			for (const entry of fs.readdirSync(baseDir, { withFileTypes: true })) {
				if (!entry.isDirectory()) continue;
				const srcDir = path.join(baseDir, entry.name, "src");
				if (fs.existsSync(srcDir)) {
					includes.push(`${base}/${entry.name}/src/**/*.ts`);
				}
			}
		} else {
			// Exact package path
			const srcDir = path.join(baseDir, "src");
			if (fs.existsSync(srcDir)) {
				includes.push(`${base}/src/**/*.ts`);
			}
		}
	}

	// Also include plugin scripts (generators are TypeScript)
	const pluginsDir = path.join(projectRoot, "plugins");
	if (fs.existsSync(pluginsDir)) {
		includes.push("plugins/**/src/**/*.ts");
		includes.push("plugins/**/scripts/**/*.ts");
	}

	return includes.sort();
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const includes = discoverIncludes(args.projectRoot);

const tsconfig = {
	$schema: "https://json.schemastore.org/tsconfig",
	_generated:
		"Generated by @orqastudio/plugin-typescript — do not edit manually. Regenerate with: orqa enforce --tsconfig",
	extends: "./tsconfig.base.json",
	compilerOptions: {
		moduleResolution: "bundler",
		target: "ESNext",
		module: "ESNext",
		verbatimModuleSyntax: true,
		noEmit: true,
	},
	include: includes,
	exclude: ["node_modules", "**/dist/**"],
};

const content = JSON.stringify(tsconfig, null, "\t") + "\n";
const outputPath = resolveOutputPath(args, "tsconfig-workspace");
writeOutput(outputPath, content);
