/**
 * tsconfig base generator for the OrqaStudio enforcement pipeline.
 *
 * Scans all rule files under --rules-dir, filters enforcement entries where
 * engine=tsconfig, and produces a self-contained tsconfig.base.json at
 * --output.
 *
 * The base compiler options come from the plugin's canonical tsconfig preset.
 * Entries from rule files can override individual compiler options via the
 * `option` and `value` fields in their enforcement entry.
 *
 * Invocation:
 *   node generate-tsconfig.ts \
 *     --project-root <path> \
 *     --output <path> \
 *     --rules-dir <path> \
 *     [--dry-run]
 */

import {
  parseArgs,
  scanRules,
  filterByEngine,
  resolveOutputPath,
  writeOutput,
  type EnforcementEntry,
  type ParsedRule,
} from "../../../shared/generator-utils";

/**
 * The canonical base compiler options provided by this plugin.
 *
 * These reflect the hand-authored base.json in src/tsconfig/base.json and are
 * the starting point before any rule overrides are applied.
 */
const BASE_COMPILER_OPTIONS: Record<string, unknown> = {
  strict: true,
  noUncheckedIndexedAccess: true,
  esModuleInterop: true,
  skipLibCheck: true,
  forceConsistentCasingInFileNames: true,
  isolatedModules: true,
  resolveJsonModule: true,
};

/**
 * Apply compiler option overrides from rule enforcement entries.
 *
 * Each entry may carry `option` (the compilerOptions key) and `value` (the
 * value to set). Entries missing either field are silently skipped.
 */
function applyRuleOverrides(
  base: Readonly<Record<string, unknown>>,
  entries: readonly EnforcementEntry[],
): Record<string, unknown> {
  const result = { ...base };
  for (const entry of entries) {
    const option = entry["option"] as string | undefined;
    const value = entry["value"];
    if (option !== undefined && value !== undefined) {
      result[option] = value;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const args = parseArgs();
const allRules = scanRules(args.rulesDir);
const relevant = filterByEngine(allRules, "tsconfig");
const entries = relevant.flatMap((r: ParsedRule) => r.enforcement);

const compilerOptions = applyRuleOverrides(BASE_COMPILER_OPTIONS, entries);

const tsconfig = {
  $schema: "https://json.schemastore.org/tsconfig",
  // Generated comment is embedded in the description field; JSON does not
  // support comments so we use a non-standard _generated key that tsc ignores.
  _generated:
    "Generated by @orqastudio/plugin-typescript — do not edit manually.",
  compilerOptions,
};

const content = JSON.stringify(tsconfig, null, 2) + "\n";
const outputPath = resolveOutputPath(args, "tsconfig");
writeOutput(outputPath, content);
