/**
 * `@orqastudio/plugin-typescript`
 *
 * TypeScript development infrastructure plugin. Provides tsconfig presets that
 * projects extend from:
 *   - `@orqastudio/plugin-typescript/tsconfig/base.json`
 *   - `@orqastudio/plugin-typescript/tsconfig/library.json`
 *   - `@orqastudio/plugin-typescript/tsconfig/app.json`
 *
 * ESLint and tsconfig enforcement configs are generated at install time by the
 * generator scripts in `scripts/`. Configs are written to `.orqa/configs/` and
 * re-generated by the daemon watcher when rule files change.
 */
