//! Message domain types for the OrqaStudio engine.
//!
//! Defines structs and enums for chat messages within a session, including roles,
//! content types, stream status, and full-text search results over message history.
//! These types flow from the database through the Tauri IPC boundary to the frontend.

use serde::{Deserialize, Serialize};

/// A single message block within a session, persisted to the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Database row ID.
    pub id: i64,
    /// ID of the session this message belongs to.
    pub session_id: i64,
    /// Role of the message author (user, assistant, or system).
    pub role: MessageRole,
    /// Content type of this message block.
    pub content_type: ContentType,
    /// Text or structured content, depending on `content_type`.
    pub content: Option<String>,
    /// Provider-assigned tool call ID (for tool use/result blocks).
    pub tool_call_id: Option<String>,
    /// Name of the tool being called or returning a result.
    pub tool_name: Option<String>,
    /// JSON-serialized tool input arguments.
    pub tool_input: Option<String>,
    /// Whether the tool invocation returned an error result.
    pub tool_is_error: bool,
    /// Index of the LLM turn that produced this block (0-based).
    pub turn_index: i32,
    /// Index of this block within its turn (0-based).
    pub block_index: i32,
    /// Streaming state of this message block.
    pub stream_status: StreamStatus,
    /// Input tokens consumed by the LLM turn (populated on turn completion).
    pub input_tokens: Option<i64>,
    /// Output tokens generated by the LLM turn (populated on turn completion).
    pub output_tokens: Option<i64>,
    /// ISO-8601 timestamp when this message was created.
    pub created_at: String,
}

/// The role of the message author in the conversation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// Message sent by the human user.
    User,
    /// Response generated by the LLM assistant.
    Assistant,
    /// System-level context injected before the conversation.
    System,
}

/// The content type of a message block.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ContentType {
    /// Plain text content.
    Text,
    /// Tool invocation request from the assistant.
    ToolUse,
    /// Result of a tool invocation.
    ToolResult,
    /// Extended thinking block (Claude-specific).
    Thinking,
    /// Inline image content.
    Image,
}

/// The streaming state of a message block.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StreamStatus {
    /// Block is being streamed and has not yet completed.
    Pending,
    /// Block has been fully received and committed.
    Complete,
    /// Streaming terminated due to an error.
    Error,
}

/// Alias for the message primary key type, used in cross-module references.
pub type MessageId = i64;

/// A full-text search result over message history.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    /// ID of the matching message.
    pub message_id: i64,
    /// ID of the session containing the match.
    pub session_id: i64,
    /// Title of the session, if set.
    pub session_title: Option<String>,
    /// Raw content of the matching message block.
    pub content: String,
    /// Highlighted snippet with match markers for display.
    pub highlighted: String,
    /// Relevance rank from the FTS engine (higher is more relevant).
    pub rank: f64,
}
