//! Streaming event domain types for the OrqaStudio engine.
//!
//! Defines the StreamEvent enum representing all events that flow from the sidecar
//! through the Tauri Channel<T> to the frontend during an LLM inference session.
//! Each variant maps to a TypeScript discriminated union on the frontend side.

use serde::{Deserialize, Serialize};

/// Streaming events that flow through `Channel<T>` from the sidecar to the frontend.
///
/// Each variant is tagged with a `type` field and optional `data` content,
/// matching the TypeScript `StreamEvent` discriminated union.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "data")]
#[serde(rename_all = "snake_case")]
pub enum StreamEvent {
    /// Signals the start of a new streaming turn.
    StreamStart {
        /// Database ID of the message block created for this turn.
        message_id: i64,
        /// Model identifier resolved by the provider (may differ from requested).
        resolved_model: Option<String>,
    },
    /// A fragment of text content generated by the model.
    TextDelta {
        /// Incremental text content to append.
        content: String,
    },
    /// A fragment of extended thinking content.
    ThinkingDelta {
        /// Incremental thinking text to append.
        content: String,
    },
    /// The model has started a tool call.
    ToolUseStart {
        /// Provider-assigned tool call identifier.
        tool_call_id: String,
        /// Name of the tool being invoked.
        tool_name: String,
    },
    /// An incremental fragment of tool input JSON.
    ToolInputDelta {
        /// Provider-assigned tool call identifier this delta belongs to.
        tool_call_id: String,
        /// Incremental JSON string fragment to append.
        content: String,
    },
    /// The result of a completed tool invocation.
    ToolResult {
        /// Provider-assigned tool call identifier.
        tool_call_id: String,
        /// Name of the tool that produced this result.
        tool_name: String,
        /// Tool output as a string (JSON or plain text).
        result: String,
        /// Whether the tool invocation returned an error.
        is_error: bool,
    },
    /// A single content block within the turn has completed.
    BlockComplete {
        /// Index of the completed block within the turn (0-based).
        block_index: i32,
        /// Content type of the completed block (e.g. `"text"`, `"tool_use"`).
        content_type: String,
    },
    /// The full LLM turn has completed with token counts.
    TurnComplete {
        /// Number of input tokens consumed by the model for this turn.
        input_tokens: i64,
        /// Number of output tokens generated by the model for this turn.
        output_tokens: i64,
    },
    /// The stream was terminated due to an error.
    StreamError {
        /// Machine-readable error code.
        code: String,
        /// Human-readable error description.
        message: String,
        /// Whether the session can be resumed after this error.
        recoverable: bool,
    },
    /// The stream was cancelled by the user or system.
    StreamCancelled,
    /// Emitted when the sidecar requests approval for a write or execute tool.
    ///
    /// The frontend must call `stream_tool_approval_respond` with the matching
    /// `tool_call_id` to unblock the stream loop.
    ToolApprovalRequest {
        /// Provider-assigned tool call identifier for this request.
        tool_call_id: String,
        /// Name of the tool awaiting approval.
        tool_name: String,
        /// JSON string of the tool parameters, for display in the UI.
        input: String,
    },
    /// Emitted after a turn completes when a process compliance violation is detected.
    ///
    /// Violations are warnings only — they do not block execution. The frontend
    /// should display them to draw attention to documentation-first process failures.
    ProcessViolation {
        /// Machine-readable check identifier (e.g. `"docs_before_code"`).
        check: String,
        /// Human-readable description of the violation.
        message: String,
    },
    /// Emitted when the session title is auto-generated from conversation content.
    ///
    /// Only fired when the title was not manually set by the user. The frontend
    /// should update the session title in its store without marking it as manual.
    SessionTitleUpdated {
        /// ID of the session whose title was updated.
        session_id: i64,
        /// New auto-generated title.
        title: String,
    },
    /// Emitted when the system prompt is sent to the model at the start of a turn.
    ///
    /// Carries both the optional user-supplied custom prompt and the governance
    /// prompt injected by the backend, plus the combined character count.
    SystemPromptSent {
        /// Optional user-supplied custom system prompt.
        custom_prompt: Option<String>,
        /// Governance system prompt injected by the backend.
        governance_prompt: String,
        /// Total character count of both prompts combined.
        total_chars: i64,
    },
    /// Emitted when prior conversation messages are injected as context.
    ///
    /// The `messages` field is a JSON array of `{role, content}` objects suitable
    /// for rendering in a dialog on the frontend.
    ContextInjected {
        /// Number of messages injected as context.
        message_count: i32,
        /// Total character count of all injected messages.
        total_chars: i64,
        /// JSON array of `{role, content}` objects for dialog display.
        messages: String,
    },
}
