// GENERATED by @orqastudio/plugin-typescript — do not edit manually.
// Source: .orqa/learning/rules/ (filtered by engine: eslint)
// Regenerated by daemon watcher on rule file changes.

import tseslint from "typescript-eslint";
import sveltePlugin from "eslint-plugin-svelte";
import jsdocPlugin from "eslint-plugin-jsdoc";
import globals from "globals";

export default tseslint.config(
  // ── Layer 1: TypeScript base ──────────────────────────────────────────
  // typescript-eslint recommended + per-rule overrides from enforcement rules.
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts"],
    rules: {

    },
  },
  {
    files: ["**/*.test.ts", "**/*.test.js", "**/__tests__/**"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["**/*.worker.ts", "**/logger.ts", "**/dev-console.ts"],
    rules: {
      "no-console": "off",
    },
  },

  // ── Layer 2: Svelte ───────────────────────────────────────────────────
  // Svelte flat/recommended + TypeScript parser for .svelte files.
  ...sveltePlugin.configs["flat/recommended"],
  {
    files: ["**/*.svelte", "**/*.svelte.ts"],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {

    },
  },
  // Library components use consumer-provided hrefs — SvelteKit resolve() doesn't apply.
  {
    files: ["libs/svelte-components/**/*.svelte"],
    rules: {
      "svelte/no-navigation-without-resolve": "off",
    },
  },

  // ── Layer 3: Environment globals ──────────────────────────────────────
  // Tauri apps run in both browser (webview) and node (build tooling).
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  // ── Layer 4: Documentation enforcement ───────────────────────────────
  // Every exported function and class must have a JSDoc description.
  jsdocPlugin.configs["flat/recommended-typescript"],
  {
    files: ["**/*.ts", "**/*.svelte.ts"],
    rules: {
      "jsdoc/require-jsdoc": ["warn", {
        require: {
          FunctionDeclaration: true,
          MethodDefinition: true,
          ClassDeclaration: true,
        },
        publicOnly: true,
      }],
      "jsdoc/require-description": "warn",
    },
  },

  // ── Layer 5: Ignores ──────────────────────────────────────────────────
  {
    ignores: [
      "build/",
      ".svelte-kit/",
      "node_modules/",
      "dist/",
      "**/dist/**",
    ],
  },
);
